# 12/6/20

# Task 1 - Lexicons

In [1]:
#lexicon --collection of words/phrases + information (POS; tense Definitions..)
#lexicon has lexicon entries -- each entry is word/phrase --has a headword(lemma)+information

# STOPWORDS
import nltk
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [2]:
# CMU Wordlist

import nltk
entries = nltk.corpus.cmudict.entries()
len(entries)

133737

In [3]:
# Wordnet

from nltk.corpus import wordnet as wn
wn.synsets('motorcar')

[Synset('car.n.01')]

In [4]:
from nltk.corpus import wordnet as wn
wn.synsets('bike')

[Synset('motorcycle.n.01'), Synset('bicycle.n.01'), Synset('bicycle.v.01')]

In [5]:
from nltk.corpus import wordnet as wn
wn.synsets('ship')

[Synset('ship.n.01'),
 Synset('transport.v.04'),
 Synset('ship.v.02'),
 Synset('embark.v.01'),
 Synset('ship.v.04'),
 Synset('ship.v.05')]

In [6]:
wn.synset('car.n.01').lemma_names()

['car', 'auto', 'automobile', 'machine', 'motorcar']

In [7]:
#Simple text classifier

def gender_features(word):
    return {'last_letter':word[-1]}

In [8]:
gender_features('Obama')

{'last_letter': 'a'}

In [9]:
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+[(name, 'female') for name in names.words('female.txt')])

In [10]:
import random 
random.shuffle(labeled_names)

In [11]:
featuresets = [(gender_features(n),gender) for (n,gender) in labeled_names]

In [12]:
train_set, test_test = featuresets[500:],featuresets[:500]

In [13]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [14]:
classifier.classify(gender_features('john'))

'male'

In [15]:
classifier.classify(gender_features('kaavya'))

'female'

In [16]:
classifier.classify(gender_features('virat'))

'male'

In [17]:
print(nltk.classify.accuracy(classifier,test_test))

0.758


In [18]:
#Vectorize and cosine similarity

from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good optical character recognition engine" , "optical character recognition in significant"]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [19]:
vocab = vect.vocabulary_

In [20]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key,vocab[key]))

character:0
engine:1
good:2
in:3
is:4
optical:5
recognition:6
significant:7
tessaract:8


In [21]:
print(vect.transform(["this is a good optical illusion"]).toarray())

[[0 0 1 0 1 1 0 0 0]]


In [22]:
print(vect.transform(corpus).toarray())

[[1 1 1 0 1 1 1 0 1]
 [1 0 0 1 0 1 1 1 0]]


In [23]:
print(vect.transform(["My name is kaavya and I am doing M.Tech"]).toarray())

[[0 0 0 0 1 0 0 0 0]]


In [24]:
print(vect.transform(corpus).toarray())

[[1 1 1 0 1 1 1 0 1]
 [1 0 0 1 0 1 1 1 0]]


In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
similarity = cosine_similarity(vect.transform(["google cloud vision is a character recognition engine"]).toarray(),vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [27]:
print(similarity)

[[0.89442719]]


In [28]:
similarity1 = cosine_similarity(vect.transform(["Artificial intelligence is a branch of computer science"]).toarray(),vect.transform(["machine learning is a subset of artificial intelligence"]).toarray())

In [29]:
print(similarity1)

[[1.]]
